Merge before release (#22)
* custom menu handling

- manual configuration of cmu_custom_menu for HA and non HA
- removed support for start/stop for both primary and secondary at same time
- qmgr to print useful info and not just emptiness

* adding sched HA fix

- check for PBS server before restarting scheduler
- some more info in documentation
- added missing path to PBS command
- removing "

* some more minor fixes

some more minor fixes

* moving everything to hpcm_pbspro_connector folder

* Updated README (final draft), remove user dependency for provisioning

* README link on main page

* Reverting OS provisioning support for now.

* Renaming HA to Failover

* Renaming HA to Failover

diff --git a/hpcm_pbspro_connector/bin/hpcm_pbs_sched b/hpcm_pbspro_connector/bin/hpcm_pbs_sched
--- a/hpcm_pbspro_connector/bin/hpcm_pbs_sched
+++ b/hpcm_pbspro_connector/bin/hpcm_pbs_sched
@@ -42,47 +42,48 @@
 #  2) Script is executed on the HPCM Management Node.
 
 # Purpose:
-# This script is used to create a node_state file that organizes
-# the registered PBS nodes into their respective states (free, busy,
-# job-busy, down, offline, etc). The node_state file will be used
-# as input for the ActionAndAlertsFile.txt
-# /opt/cmu/bin/cmu_submit_extended_metrics -f/tmp/node_state
 
 # Source in PBS specific environment variables from pbs.conf
 if [ -f /etc/pbs.conf ]; then
-    . /etc/pbs.conf
+   . /etc/pbs.conf
 else
-    echo "Unable to find /etc/pbs.conf"
-    exit 1
+   echo "Unable to find /etc/pbs.conf"
+   exit 1
 fi
 
-# Define CMU_PBSPRO_CONNECTOR, CMU_PATH
-CMU_PBSPRO_CONNECTOR=/opt/clmgr/contrib/hpcm_pbspro_connector
+# Define CMU_PATH
 CMU_PATH=/opt/clmgr/bin
-CMU_SUBMIT_EXTENDED_METRIC=${CMU_PATH}/cmu_submit_extended_metrics
 
-declare -A node_state
+# Simple Usage statement
+Usage() {
+         cat <<EOF
+Usage: `basename $0`
 
-state_file=${CMU_PBSPRO_CONNECTOR}/tmp/extended_metric_node_state
+EOF
+    exit 0
+}
 
-rm ${state_file}
-
-state=`${PBS_EXEC}/bin/pbsnodes -a | grep -e "^[[:alnum:]]" -e state | sed '1~2 {N;s/\n/ /g}' | awk '{print $1";"$4}'`
-
-# Iterate through the registered PBS Professional nodes. associate
-# nodes to the known node_state
-for s in `echo "$state"` ; do
-   y=`echo $s | awk 'BEGIN { FS = ";" } ; { print $1 }'`
-   z=`echo $s | awk 'BEGIN { FS = ";" } ; { print $2 }'`
-   node_state+=( ["$z"]=" $y" )
+while getopts h opt; do
+    case $opt in
+        h) Usage ;;
+    esac
 done
 
-# Construct the state_file, which will be read in by the
-# cmu_submit_extended_metric command
-for a in "${!node_state[@]}" ; do
-    echo "BEGIN_NODE ${node_state[$a]}
-node_state $a" >> ${state_file}
-done
+if [ -n "$PBS_PRIMARY" ]; then
+    ping -c 3 $PBS_PRIMARY > /dev/null 2>&1
+    if [ $? -eq 0 ]; then
+       echo $PBS_PRIMARY
+       exit 0
+    fi
+    ping -c 3 $PBS_SECONDARY > /dev/null 2>&1
+    if [ $? -eq 0 ]; then
+       echo $PBS_SECONDARY
+       exit 0
+    fi
+else
+    echo $PBS_SERVER
+    exit 0
+fi
 
-# Execute the cmu_submit_extended_metric
-${CMU_SUBMIT_EXTENDED_METRIC} -f ${state_file}
+echo "undefined"
+
